services:

  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: airflow-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  airflow-init:
    image: apache/airflow:2.9.3
    container_name: airflow-init

    entrypoint: /bin/bash

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "6tCbbQdW_VyQAVDsYiwGm0hD59mPEUrZBhexfdSjFQ0="
      AIRFLOW_UID: 50000

    command:
      - -c
      - |
        airflow db migrate

        airflow users create \
          --username admin \
          --password admin \
          --firstname Airflow \
          --lastname Admin \
          --role Admin \
          --email admin@example.com || true

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

  airflow-webserver:
    image: apache/airflow:2.9.3
    container_name: airflow-webserver

    depends_on:
      - airflow-init

    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "6tCbbQdW_VyQAVDsYiwGm0hD59mPEUrZBhexfdSjFQ0="
      #python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"                
      AIRFLOW__CORE__LOAD_EXAMPLES: "True"
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
      AIRFLOW_UID: 50000

    ports:
      - "8080:8080"
    command: webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  airflow-scheduler:
    image: apache/airflow:2.9.3
    container_name: airflow-scheduler
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "6tCbbQdW_VyQAVDsYiwGm0hD59mPEUrZBhexfdSjFQ0="
      # python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"                
      AIRFLOW_UID: 50000
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    restart: unless-stopped

  airflow-worker:
    image: apache/airflow:2.9.3
    container_name: airflow-worker

    depends_on:
      - airflow-init

    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: "6tCbbQdW_VyQAVDsYiwGm0hD59mPEUrZBhexfdSjFQ0="
      # python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"                
      AIRFLOW_UID: 50000
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth

    command: airflow celery worker

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins

    restart: unless-stopped

volumes:
  postgres-db-volume:
